### ISSUE TITLE
R packaged limma not found

### ISSUE THREAD

**Issue by Bjoernsen** [Victorian-Bioinformatics-Consortium/degust#10]
Hi,

the back-end analysis did not work for me, because `limma` was not installed.
But this problem was not fixed, after installing `limma` (and `edgeR`).

I was able to fix this issue by changing the R library path hard coded in `app/backend/r-json.hs`

Original line 262:

```
(_,out,err,pid) <- runInteractiveProcess "Rscript" ["--vanilla",inF] Nothing
                             (Just [("R_LIBS_SITE","/bio/sw/R:")])
```

New line 262:

```
(_,out,err,pid) <- runInteractiveProcess "Rscript" ["--vanilla",inF] Nothing
                             (Just [("R_LIBS_SITE","/path/to/my/R/library:")])
```

**Comment by drpowell** [comment]
Not a problem on the new site : degust.erc.monash.edu
