### ISSUE TITLE
Need Help for Degust Tool

### ISSUE THREAD

**Issue by rahdayal** [Victorian-Bioinformatics-Consortium/degust#20]
Hi Sir

Its very painful from last one week , try to integrate the degust tool but unable to do so. Download the degust.py and install python on system and xampp. Then run degust.py with parameter  csv file. 
But when i am printing the args variable,
Its showing :- 

Namespace(avg=None, counts=[], csvfile=, cuffdiff=False, fdr='adj.P.Val', info=None, link_col=None, link_url=None, logFC=None, name='Unnamed', notour=None, out=’, mode 'w' at 0x012A5078>,primary='pri', tab=False)

Thanks

**Comment by drpowell** [comment]
I think this is a problem with xampp which I can't really diagnose

**Comment by rahdayal** [comment]
Thanks david. Actuall, your given command helped me. i got the solution. One thing i just want to know. that why your html and my html is have different result. 
and above all thank you so much for the help :+1:
