### ISSUE TITLE
Bug ? Counts used as fold changes

### ISSUE THREAD

**Issue by colindaven** [Victorian-Bioinformatics-Consortium/degust#24]
Hi,

I believe I have found a bug.

If I have two replicates
sample_Rep1
sample_Rep2
in the csv things work as expected.

If however the headers are
sample
sample_Rep2
then the fold changes are not computed (or not used), and the fold change is the same as the first count. Implications - false "fold changes" as very wrong, and always positive.

This behaviour can be corrected by renaming samples as sample_Rep1 and sample_Rep2.

cheers

**Comment by drpowell** [comment]
Thanks I think the bug might be if a replicate is named the same as one of the created condition names.  This is a little tricky to fix - I'll give it some thought.

**Comment by colindaven** [comment]
Perhaps the pragmatic solution - Degust condition names could be checked and not accepted if they have the same name as one of the replicates.

**Comment by tseemann** [comment]
I think @colindaven idea of rejecting duplicate names is a good one.  

But "evil me" says you deserve everything you get if you name conditions the same as samples ;-)

**Comment by drpowell** [comment]
Error check added 

https://github.com/drpowell/degust2/commit/6fc425d495923393bd52fc440bd0772634715336
