### ISSUE TITLE
Cannot view data from configuration window

### ISSUE THREAD

**Issue by JakeGoodall** [Victorian-Bioinformatics-Consortium/degust#31]
Hi, 

I was wondering if Degust is currently up and running as intended. I can upload my data (.csv file) to the server but whenever I try to either save or view the data from the 'configuration' window all prior input is reset and I am left to fill out the configuration window again. I've attempted to view both my personal data and also your example .csv data file, both of which are unsuccessful. Degust has worked very well for me in the past, so I'm not sure what I am doing wrong, any insights? 

Regards,
Jake Goodall

**Comment by drpowell** [comment]
Hi Jake, it should be running fine - I've been using it today.  Can you share a link that isn't working for you?  (david.powell@monash.edu if you prefer)
