### ISSUE TITLE
Export differential expression results as ODF format

### ISSUE THREAD

**Issue by AMChalkie** [Victorian-Bioinformatics-Consortium/degust#33]
I'd really like to see export of differential expression into an ODF file (like GenePattern). Allows downstream functionality (limited I know), but it is a standard format and I think thats useful as a way to report supplementary data (if not just using the degust HTML).

**Comment by AMChalkie** [comment]
We've been writing some R code for outputting from degust R code => ODF file format. Will share with degust and limma people once we're happy with it.

**Comment by AMChalkie** [comment]
As promised/threatened here is code from Josh White to produce an odf file from the differential expression results. Please feel free to use with absolutely no obligations. Obviously we would love to see degust include this output in the future.


[degust2odf.R.txt](https://github.com/Victorian-Bioinformatics-Consortium/degust/files/345752/degust2odf.R.txt)

**Comment by drpowell** [comment]
That looks great, I'll look to incorporate it soon

**Comment by drpowell** [comment]
Added ODF download support to new version of degust
https://github.com/drpowell/degust2/commit/c239dd66fe0d733d36ed484c8a85066303626a5d

Try out beta version here : http://dna.med.monash.edu:4000/

**Comment by AMChalkie** [comment]
Hi David,

Getting a failed/network error when trying to download tsv/odf/etc. Due to not being on Monash intranet?

/alistair

**Comment by drpowell** [comment]
I don't think so, it is all local in the browser.  What browser are you using?  Can you share a link that isn't working?  (email if you want to keep it private)

**Comment by AMChalkie** [comment]
Chrome isn't working. Safari is - but doesn't pop up a save-as.

**Comment by drpowell** [comment]
Should now be working in chrome.  I couldn't figure out how to make it popup a "save as" in safari
