### ISSUE TITLE
Enhancement: Plot all values for a selected gene / publication ready figure

### ISSUE THREAD

**Issue by AMChalkie** [Victorian-Bioinformatics-Consortium/degust#34]
Hi guys,

In the interest of seeing all the data, and in plotting key genes of interest for a publication, an option to do the following would be super helpful for the biologists. Especially when assessing why someones gene of interest isn't significantly DE.

Given a gene:
- Plot all data points for that gene, grouped by sample class. 
- Possibly add p-value between the groups PRISM style
- Export this as pdf/similar in high res.

Cheers
/Alistair

**Comment by tseemann** [comment]
@drpowell 

I just did a demo of Degust at #NGS2016 and @macmanes suggested a feature he really wants is a "per gene" summary, which is pretty much what @AMChalkie suggested above.

He would like a box plot with points included, as he has 17 replicates per condition!

I know these are easy in R, and that for Degust it would have to be on the client browser, but this seems to be something people would like.

**Comment by genomematt** [comment]
I will third this.  Looking at spread in expected DE is something I do a fair bit of when diagnosing experiments lacking an anticipated biological response.  Can be really useful for working out if it is overall variability or outliers that are at issue.  Would be good to be able to do directly in degust

**Comment by drpowell** [comment]
Added a new plot for expression on hover on heatmap, table or ma-plot.  (select "Gene" above Option). 

On new site : http://dna.med.monash.edu:4000/

**Comment by drpowell** [comment]
Typo fixed.  I had a bug guessing the size to save as which should be fixed (though that is tricky to get right).  If you manually specify a size it should work.
