### ISSUE TITLE
NA in csv produces a data point without name and description

### ISSUE THREAD

**Issue by AMChalkie** [Victorian-Bioinformatics-Consortium/degust#38]
Hi David,
The following line results in a datapoint with "","" as Name/Description instead of NA,NA.
NA,NA,28588,3846,4425,190407,8737,15214

A warning when degust sees NA in the primary key might be useful here - regardless of if NA should be in the input file at all :)

Cheers
/Alistair

**Comment by drpowell** [comment]
Fixed
