### ISSUE TITLE
Enhancement: download CSV static link 

### ISSUE THREAD

**Issue by colindaven** [Victorian-Bioinformatics-Consortium/degust#39]
Hi,

Degust is nice and quite easy to use, and at some point users like to download CSVs. This has proven very troublesome with big CSVs with 50-100k + features and lots of conditions. In other words, the browser tends to die if download sizes are over 20mb  or so.

One idea around this might be to calculate and provide a stable link, which could be downloaded via an alternative like wget. Else, do you know any (good) 64 bit browsers which can handle the strain ? Chrome is bad at this in my experience, Firefox occasionally gets the job done.

Thanks.

**Comment by drpowell** [comment]
I *think* this works via the blob url on the new site : degust.erc.monash.edu
