### ISSUE TITLE
Enhancement: Keeping track of input files

### ISSUE THREAD

**Issue by AMChalkie** [Victorian-Bioinformatics-Consortium/degust#40]
Hi,
I've got a number of degust windows, and am realising it would be useful to keep track of information about the original input file given:

a) Origional input file name+path (rather than the server side 821a6ba888daff12bf6e0dc27f747268-counts.csv)
and / or mda5sum of the original input file.

Cheers
/Alistair

**Comment by drpowell** [comment]
Use original file name in r code now.

Also, log in via twitter or google to track your files
