### ISSUE TITLE
problems uploading csv

### ISSUE THREAD

**Issue by avilella** [Victorian-Bioinformatics-Consortium/degust#45]
Hi,

I am trying to upload an example csv of raw input data. I took the one in the example, but complained it didn't have enough lines. So I modified it and added more lines like so:
```
Gene ID, name, control rep1, control rep2, treatment A rep1, treatment A rep2, EC Number
gene001, flavodoxin, 60, 40, 200, 220, 3.1.-.-
gene002, p53, 0, 4, 20, 30,
gene003, potassium uptake protein, 600, 633, 200, 220, 2.7.8.-
gene004, potassium uptake protein, 600, 633, 200, 220, 2.7.8.-
gene005, potassium uptake protein, 600, 633, 200, 220, 2.7.8.-
gene006, potassium uptake protein, 600, 633, 200, 220, 2.7.8.-
gene007, potassium uptake protein, 600, 633, 200, 220, 2.7.8.-
gene008, potassium uptake protein, 600, 633, 200, 220, 2.7.8.-
```

I then uploaded it to the system. I assign Gene ID and name as info columns, EC number column, select the treatment and controls, click 'Save' then click 'View'. See below.

The result is an empty page with no values/rows. See below.

Am I loading this data correctly?

<img width="796" alt="screen shot 2017-01-25 at 14 06 29" src="https://cloud.githubusercontent.com/assets/158007/22293472/9111a81e-e307-11e6-9a48-27ec48f9600a.png">
<img width="1204" alt="screen shot 2017-01-25 at 14 07 23" src="https://cloud.githubusercontent.com/assets/158007/22293491/b426a3b8-e307-11e6-8a71-eb8572f0ef8a.png">

**Comment by avilella** [comment]
I tried it with combination of only 'Gene ID' as label, or only 'name' as label, no luck.

I tried it with a larger file with about 25000 rows, same result.

**Comment by colindaven** [comment]
I'm not a developer here, but have used extensively. 

To me I would avoid having a space in the column names
try
control rep1
as
control_rep1

Colin

**Comment by avilella** [comment]
Tried that, same result. Does anybody have a working example?

**Comment by avilella** [comment]
I see there are examples on the website for the analysed values. In my case I want to load a csv with the raw counts, but I can't get it to work. Any ideas?

**Comment by colindaven** [comment]
Thats a shame. Your data all look ok to me. We installed locally (very hard) and used extensively. 

Chief problems were: spaces in any field, column names being the same as condition names (or similar), header being ignored, etc.

You definitely need to put a CSV with the raw counts in.

**Comment by avilella** [comment]
Hi Colin,

Have you got a working example .csv that I can start with? If I have a
working one, I can reverse engineer the issue from it.

A.

**Comment by drpowell** [comment]
Turns out the problem is that the space you have in the column names after the comma.  Specifically, if it should be fine if the header row was this
 
`Gene ID,name,control rep1,control rep2,treatment A rep1,treatment A rep2,EC Number`

I'll raise a bug, and try and fix this properly soon.  Also, there is newer beta version of degust with a few new features running here : [http://dna.med.monash.edu:4000/](http://dna.med.monash.edu:4000/)

**Comment by drpowell** [comment]
Bug raised for this : https://github.com/Victorian-Bioinformatics-Consortium/degust/issues/46
