### ISSUE TITLE
Fatal error: cannot create 'R_TempDir'

### ISSUE THREAD

**Issue by carolineneof** [Victorian-Bioinformatics-Consortium/degust#56]
When trying to compare different conditions (even with the demo data), I get the error detailed below. This didn't happen before. How can I solve this issue? Thanks!

Fatal error: cannot create 'R_TempDir'

library(limma)
library(edgeR)
library(jsonlite)

counts_file <- 'uploads/728525be08b4b1c8df47f36859fa179e'
output_dir <- "/opt/degust/tmp/R-tmp20211105-1-17ved3w"
count_cols <- c('GppX-rep1','GppX-rep2','cdhR-rep1','cdhR-rep2','luxS-rep1','luxS-rep2','luxS-rep3','wt-rep1','wt-rep2','wt-rep3')
design <- matrix(c(c(0,0,1,1,0,0,0,0,0,0),c(1,1,0,0,0,0,0,0,0,0),c(0,0,0,0,1,1,1,0,0,0),c(0,0,0,0,0,0,0,1,1,1)), ncol=4, dimnames=list(c('GppX-rep1','GppX-rep2','cdhR-rep1','cdhR-rep2','luxS-rep1','luxS-rep2','luxS-rep3','wt-rep1','wt-rep2','wt-rep3'),c('cdhR','GppX','luxS','wt')))
cont.matrix <- matrix(c(c(-1,1,0,0),c(-1,0,1,0)), ncol=2, dimnames=list(c('cdhR','GppX','luxS','wt'),c('GppX','luxS')))
export_cols <- c(c('Feature','gene','product','cdhR-rep1','cdhR-rep2','GppX-rep1','GppX-rep2','luxS-rep1','luxS-rep2','luxS-rep3','wt-rep1','wt-rep2','wt-rep3','EC Number'))

# Maybe filter out samples that are not used in the model
if (FALSE) {
    # Remove columns not used in the comparison
    use.samples <- rowSums((design %*% cont.matrix)!=0)>0
    use.conditions <- colSums(design[use.samples,]!=0)>0

    count_cols <- count_cols[use.samples,drop=F]
    design <- design[use.samples, use.conditions,drop=F]
    cont.matrix <- cont.matrix[use.conditions,,drop=F]
}

**Comment by drpowell** [comment]
There was an issue with the server filling up the disk.  It should be fixed now.  Thx for the report
